# This configuration file defines the GitHub runner requirements for each E2E test or set of E2E tests.
#
# Each test entry details the runner environment (Docker or Kubernetes), Go test command, and triggers
# that determine under what conditions the test should be executed (e.g., on push or nightly builds).
#
# This file is used by CI workflows to run E2E tests depending on the trigger and the test type. 

# Example of 1 runner for all tests in integration-tests/smoke/ocr_test.go
- id: run_all_in_ocr_tests_go 
  path: integration-tests/smoke/ocr_test.go
  test-type: docker
  runs-on: ubuntu-latest
  cmd: go test integration-tests/smoke/ocr_test.go -test.parallel=1 -timeout 30m -count=1 -json
  # workflow: [nightly-e2e-tests.yml]
  trigger: ["push", "nightly"]

# Example of 2 separate runners for the same test file but different tests. Can be used if tests if are too heavy to run on the same runner
- id: run_TestOCRv2Request_in_ocr2_test_go
  path: integration-tests/smoke/ocr2_test.go
  test-type: docker
  runs-on: ubuntu-latest
  cmd: go test integration-tests/smoke/ocr2_test.go -test.run ^TestOCRv2Request$ -test.parallel=1 -timeout 30m -count=1 -json
- id: run_TestOCRv2Basic_in_ocr2_test_go
  path: integration-tests/smoke/ocr2_test.go
  test-type: docker
  runs-on: ubuntu-latest
  cmd: go test integration-tests/smoke/ocr2_test.go -test.run ^TestOCRv2Basic$ -test.parallel=1 -timeout 30m -count=1 -json

# Example of configuration for running a test in Kubernetes Remote Runner
- id: run_TestOCRSoak_in_ocr_test_go
  path: integration-tests/smoke/ocr2_test.go
  test-type: k8s-remote-runner
  runs-on: ubuntu-latest
  cmd: go test integration-tests/soak/ocr_test.go -test.run ^TestOCRSoak$ -test.parallel=1 -timeout 30m -count=1 -json
