[OCR]
ocrish_field = "stefan"

[Logging]
test_log_collect=false
test_log_level="DEBUG"
log_stream_log_targets=["file"]
#loki_tenant_id
#loki_url
#loki_basic_auth
#grafana_url
#grafana_data_source
run_id="mietek"

[Network]
selected_networks=["simulated"]
#evm_http_urls=
#evm_ws_urls=
#evm_keys=

[ChainlinkImage]
image="public.ecr.aws/chainlink/chainlink"
version="2.7.0"

[PrivateEthereumNetwork]
consensus_type="pos"
consensus_layer="prysm"
execution_layer="geth"
wait_for_finalization=false

[PrivateEthereumNetwork.EthereumChainConfig]
seconds_per_slot=12
slots_per_epoch=6
genesis_delay=15
validator_count=8
chain_id=1337
addresses_to_fund=["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]