[LogPoller]
[LogPoller.General]
generator = "looped"
contracts = 10
events_per_tx = 10

[LogPoller.Chaos]
experiment_count = 10

[LogPoller.Looped]
execution_count = 300
min_emit_wait_time_ms = 100
max_emit_wait_time_ms = 500

[LogPollerWasp]
call_timeout = "3m"
rate_limit_unit_duration = "2s"
LPS = 30
duration = "1m"