[Automation]
[Automation.General]
number_of_nodes=6
duration=900
block_time=1
number_of_events=1
spec_type="minimum"
chainlink_node_log_level="info"
use_prometheus=false

[[Automation.Load]]
number_of_upkeeps=5
number_of_events = 1
number_of_spam_matching_events = 1
number_of_spam_non_matching_events = 0
check_burn_amount = 0
perform_burn_amount = 0
upkeep_gas_limit = 1000000
shared_trigger = false

[[Automation.Load]]
number_of_upkeeps=5
number_of_events = 1
number_of_spam_matching_events = 0
number_of_spam_non_matching_events = 1
check_burn_amount = 0
perform_burn_amount = 0
upkeep_gas_limit = 1000000
shared_trigger = true

[Pyroscope]
enabled=false