[[EVM]]
ChainID = '84531'
MinContractPayment = '0'
NoNewHeadsThreshold = '30s'
ChainType = 'optimismBedrock'
LogPollInterval = '2s'
FinalityDepth = 200
MinIncomingConfirmations = 3
[EVM.GasEstimator]
EIP1559DynamicFees = true
Mode = 'BlockHistory'
BumpThreshold = 3
PriceMin = '1 wei'
[EVM.GasEstimator.BlockHistory]
BlockHistorySize = 24
[EVM.Transactions]
ResendAfterThreshold = '30s'
[EVM.HeadTracker]
SamplingInterval = '1s'
HistoryDepth = 300
[EVM.NodePool]
SyncThreshold = 10