ChainID = '1029'
ChainType = 'bttc'
FinalityDepth = 500 
# blocks are generated every 2-4s 
LogPollInterval = '2s'

[GasEstimator] 
Mode = 'BlockHistory'
EIP1559DynamicFees = false
PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
PriceMin = '0.009 ether'

[GasEstimator.BlockHistory]
# how many blocks we want to keep in memory to calculate gas price
# # Average block time of 2s
BlockHistorySize = 24

[Transactions]
ResendAfterThreshold = '30s'

[HeadTracker]
# re-org for bttc is really high so we want to check for the block where reorg happens
HistoryDepth = 500

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1