ChainID = '1029'
# Finality Depth is insanely high (https://github.com/bttcprotocol/bttc/blob/master/params/network_params.go#L60) 
FinalityDepth = 9000
# blocks are generated every 2-4s 
LogPollInterval = '2s'
# Blocks are only emitted when a transaction happens / no empty blocks
NoNewHeadsThreshold = '0'

[GasEstimator]
EIP1559DynamicFees = false

[GasEstimator.BlockHistory]
# how many blocks we want to keep in memory to calculate gas price
# # Average block time of 2s
BlockHistorySize = 24

[Transactions]
ResendAfterThreshold = '30s'

[HeadTracker]
# re-org for bttc is really high so we want to check for the block where reorg happens
HistoryDepth = 9000

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1