ChainType = 'bttc'
ChainID = '1029'
FinalityDepth = 500 
# blocks are generated every 2-4s 
LogPollInterval = '2s'
LinkContractAddress = "0xC391D8FFa7a05723C85f160Bd1Fe411C5898b2a4"

[GasEstimator] 
Mode = 'BlockHistory'
EIP1559DynamicFees = false
PriceDefault = '15 mwei'
PriceMin = '9 mwei' 

[GasEstimator.BlockHistory]
# how many blocks we want to keep in memory to calculate gas price
BlockHistorySize = 24

[HeadTracker]
# re-org for bttc is really high so we want to check for the block where reorg happens
HistoryDepth = 500

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1
