ChainID = '1029'
ChainType = 'bttc'
FinalityDepth = 500 
# blocks are generated every 2-4s 
LogPollInterval = '2s'
LinkContractAddress = '0x95b3197262301ab8e79c21662a41c868f2c5c368'

[GasEstimator.BlockHistory]
# how many blocks we want to keep in memory to calculate gas price
# # Average block time of 2s
BlockHistorySize = 24

[Transactions]
ResendAfterThreshold = '30s'

[HeadTracker]
# re-org for bttc is really high so we want to check for the block where reorg happens
HistoryDepth = 500

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1