ChainID = '2221'
FinalityDepth = 1
LogPollInterval = '6s'
NoNewHeadsThreshold = '1m'
MinIncomingConfirmations = 1

[GasEstimator]
EIP1559DynamicFees = false
PriceMin = '1 wei'
BumpMin = '100 wei'

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[Transactions]
ResendAfterThreshold = '30s'

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1