ChainID = '59141'
FinalityDepth = 28800
NoNewHeadsThreshold = '0'

[GasEstimator]
EIP1559DynamicFees = true
BumpPercent = 10
PriceMin = '1 wei'

[Transactions]
ResendAfterThreshold = '3m'

[HeadTracker]
HistoryDepth = 28800
