ChainID = '5003'
LinkContractAddress = '0x567B10818d6fdD653F0331b5Df08968Ca826bE88'
FinalityDepth = 200
LogPollInterval = '2s'
NoNewHeadsThreshold = '0'
MinIncomingConfirmations = 1

[HeadTracker]
HistoryDepth = 300

[GasEstimator]
Mode = 'L2Suggested'
PriceMin = '0.05 gwei' 
PriceMax = '500 gwei'
BumpThreshold = 0
LimitDefault = 6000000

[Transactions]
ResendAfterThreshold = '1m'
MaxQueued = 5000