ChainID = '5001'
ChainType = 'optimismBedrock'
LinkContractAddress = '0xB80e1F300D0260E8840A9E9017b221244974A5E5'
FinalityDepth = 200
LogPollInterval = '2s'
NoNewHeadsThreshold = '0'
MinIncomingConfirmations = 1

[HeadTracker]
HistoryDepth = 300

[GasEstimator]
Mode = 'L2Suggested'
PriceMin = '0.05 gwei' 
PriceMax = '200 gwei'
BumpThreshold = 0
LimitDefault = 6000000

