ChainID = '534351'
FinalityDepth = 10
ChainType = 'scroll'
LogPollInterval = '3s'
MinIncomingConfirmations = 1
# Scroll only emits blocks when a new tx is received, so this method of liveness detection is not useful
NoNewHeadsThreshold = '0'

[GasEstimator]
EIP1559DynamicFees = true
PriceMin = '1 wei'
BumpMin = '100 wei'

[GasEstimator.BlockHistory]
BlockHistorySize = 500

[HeadTracker]
HistoryDepth = 50

[OCR]
ContractConfirmations = 1
