ChainID = '324'
ChainType = 'zksync'
FinalityDepth = 1
LogPollInterval = '5s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '1m'

[GasEstimator]
EIP1559DynamicFees = true
PriceMax = 18446744073709551615
PriceMin = '1 wei'
BumpMin = '100 wei'
GasPerPubdata = '50000 wei'

[HeadTracker]
HistoryDepth = 5
