
[Common]
minimum_confirmations = 3

[NewEnvConfig]
sub_funds_link = 1
node_sending_key_funding = 10

[ExistingEnvConfig]
coordinator_address = "0x1d186B0A9b6EBd99AaE88af8893e46575Fd5BaD2"
#consumer_address = ""
#sub_id = ""
key_hash = "0x0cf74660cc616c9f40313af1fb699b862b15a86aa1787789315a66440205674e"
create_fund_subs_and_add_consumers = true
link_address = "0xB426B2Bde3ad4BEEE2f07d8d38fDe2d66EdAb943"
sub_funds_link = 1000
#node_sending_key_funding_min = 3
#node_sending_keys = [
#    "",
#    "",
#    "",
#    "",
#    "",
#    "",
#]

# 10 RPM - 1 tx request with 1 rand request in each tx every 6 seconds
[Soak]
rate_limit_unit_duration = "6s"
rps = 1
randomness_request_count_per_request = 1 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

# approx 60 RPM - 1 tx request with 3 rand requests in each tx every 3 seconds
[Load]
rate_limit_unit_duration = "3s"
rps = 1
randomness_request_count_per_request = 3 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 2 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

# approx 540 RPM - 3 tx requests per second with 4 rand requests in each tx
[Stress]
rate_limit_unit_duration = "1s"
rps = 3
randomness_request_count_per_request = 4 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

# approx 150 RPM - 1 tx request with 150 rand requests in each tx every 60 seconds
[Spike]
rate_limit_unit_duration = "1m"
rps = 1
randomness_request_count_per_request = 150 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1