
[Common]
minimum_confirmations = 3
cancel_subs_after_test_run = true
# approx 60 RPM - 1 tx request with 3 rand requests in each tx every 3 seconds
rate_limit_unit_duration = "3s"
rps = 1
randomness_request_count_per_request = 3 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 2 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

[NewEnvConfig]
sub_funds_link = 1000
node_sending_key_funding = 1000

[ExistingEnvConfig]
coordinator_address = ""
consumer_address = ""
sub_id = 1
key_hash = ""
create_fund_subs_and_add_consumers = true
link_address = ""
sub_funds_link = 10
node_sending_key_funding_min = 1
node_sending_keys = [
    "",
    "",
    "",
    "",
    "",
    "",
]