
[Common]
minimum_confirmations = 3
cancel_subs_after_test_run = true
# approx 540 RPM - 3 tx requests per second with 4 rand requests in each tx
rate_limit_unit_duration = "1s"
rps = 3
randomness_request_count_per_request = 4 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

[NewEnvConfig]
sub_funds_link = 1000
node_sending_key_funding = 1000

[ExistingEnvConfig]
coordinator_address = ""
consumer_address = ""
sub_id = 1
key_hash = ""
create_fund_subs_and_add_consumers = true
link_address = ""
sub_funds_link = 10
node_sending_key_funding_min = 1
node_sending_keys = [
    "",
    "",
    "",
    "",
    "",
    "",
]
