[general]
generator = "looped"
contracts = 2
events_per_tx = 4
use_finality_tag = false

[chaos]
experiment_count = 10

[looped]
execution_count = 100
min_emit_wait_time_ms = 200
max_emit_wait_time_ms = 500