#
# This action creates or updates a Release Preview PR that shows which changes are going to be part of the next release
# when a PR is merged into develop branch
#

name: Release Preview - Changeset

on:
  push:
    branches:
      - develop

jobs:
  cd-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      changesets_published: ${{ steps.cd-release.outputs.published }}
      changesets_publishedPackages: ${{ steps.cd-release.outputs.publishedPackages }}
    steps:
      - name: cd-release
        id: cd-release
        uses: smartcontractkit/.github/actions/cicd-changesets@re-2428/update-cicd-changeset
        with:
          # general inputs
          git-user: app-token-issuer-releng[bot]
          git-email: app-token-issuer-releng[bot]@users.noreply.github.com
          pnpm-use-cache: false
          pr-draft: true
          pr-labels: "DO_NOT_MERGE"
          pr-title: "[DO NOT MERGE] Release Preview - Changeset"
          # aws inputs
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CHAINLINK_CI_AUTO_PR_TOKEN_ISSUER_ROLE_ARN }}
          aws-lambda-url: ${{ secrets.AWS_INFRA_RELENG_TOKEN_ISSUER_LAMBDA_URL }}
