name: "Build publish Chainlink develop on private ECR"

on:
  pull_request:

jobs:
  push-chainlink-develop-goreleaser:
    runs-on:
      labels: ubuntu22.04-16cores-64GB
    outputs:
      goreleaser-metadata: ${{ steps.build-sign-publish.outputs.goreleaser-metadata }}
      goreleaser-artifacts: ${{ steps.build-sign-publish.outputs.goreleaser-artifacts }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Build, sign, and publish image
        id: build-sign-publish
        uses: ./.github/actions/goreleaser-build-sign-publish
        with:
          enable-docker-publish: "false"
          enable-goreleaser-snapshot: "true"
          goreleaser-exec: ./tools/bin/goreleaser_wrapper
          goreleaser-config: .goreleaser.develop.yaml
          goreleaser-key: ${{ secrets.GORELEASER_KEY }}
          zig-version: 0.11.0
      - name: Collect Metrics
        if: always()
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
        with:
          id: goreleaser-build-publish
          org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
          basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          this-job-name: push-chainlink-develop-goreleaser
        continue-on-error: true
