name: Monitoring

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: "./pkg/monitoring"
          args: --enable=gofmt --tests=false --exclude-use-default --timeout=5m0s
          skip-go-installation: true
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Test
        run: go test -count=1 -race -v ./pkg/monitoring/...
