name: Run Selected E2E Tests

on:
  workflow_dispatch:
    inputs:
      chainlink-version:
        description: 'Enter Chainlink version to use for the tests. Example: "v2.10.0" or sha'
        default: develop
        required: false
        type: string
      test-ids:
        description: 'Run all tests "*" by default. Or, enter test IDs to run separated by commas. Example: "run_all_in_ocr_tests_go,run_TestOCRv2Request_in_ocr2_test_go". Check all test IDs in .github/e2e-tests.yml'
        default: "*"
        required: true
        type: string

jobs:
  call-run-e2e-tests-workflow:
    name: Run E2E Tests
    uses: ./.github/workflows/run-e2e-tests-reusable-workflow.yml
    with:
      chainlink-version: ${{ github.event.inputs.chainlink-version }}
      test-ids: ${{ github.event.inputs.test-ids }}
    secrets:
      QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
